/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RPCserver_constants.h"

namespace RPC {

const RPCserverConstants g_RPCserver_constants;

RPCserverConstants::RPCserverConstants() {
}

} // namespace

