/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RPCserver_CONSTANTS_H
#define RPCserver_CONSTANTS_H

#include "RPCserver_types.h"

namespace RPC {

class RPCserverConstants {
 public:
  RPCserverConstants();

};

extern const RPCserverConstants g_RPCserver_constants;

} // namespace

#endif
