/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef printDate_H
#define printDate_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "hello_world_types.h"

namespace hello_world {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class printDateIf {
 public:
  virtual ~printDateIf() {}
  virtual void getTime(std::string& _return) = 0;
};

class printDateIfFactory {
 public:
  typedef printDateIf Handler;

  virtual ~printDateIfFactory() {}

  virtual printDateIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(printDateIf* /* handler */) = 0;
};

class printDateIfSingletonFactory : virtual public printDateIfFactory {
 public:
  printDateIfSingletonFactory(const boost::shared_ptr<printDateIf>& iface) : iface_(iface) {}
  virtual ~printDateIfSingletonFactory() {}

  virtual printDateIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(printDateIf* /* handler */) {}

 protected:
  boost::shared_ptr<printDateIf> iface_;
};

class printDateNull : virtual public printDateIf {
 public:
  virtual ~printDateNull() {}
  void getTime(std::string& /* _return */) {
    return;
  }
};


class printDate_getTime_args {
 public:

  printDate_getTime_args(const printDate_getTime_args&);
  printDate_getTime_args& operator=(const printDate_getTime_args&);
  printDate_getTime_args() {
  }

  virtual ~printDate_getTime_args() throw();

  bool operator == (const printDate_getTime_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const printDate_getTime_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const printDate_getTime_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class printDate_getTime_pargs {
 public:


  virtual ~printDate_getTime_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _printDate_getTime_result__isset {
  _printDate_getTime_result__isset() : success(false) {}
  bool success :1;
} _printDate_getTime_result__isset;

class printDate_getTime_result {
 public:

  printDate_getTime_result(const printDate_getTime_result&);
  printDate_getTime_result& operator=(const printDate_getTime_result&);
  printDate_getTime_result() : success() {
  }

  virtual ~printDate_getTime_result() throw();
  std::string success;

  _printDate_getTime_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const printDate_getTime_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const printDate_getTime_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const printDate_getTime_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _printDate_getTime_presult__isset {
  _printDate_getTime_presult__isset() : success(false) {}
  bool success :1;
} _printDate_getTime_presult__isset;

class printDate_getTime_presult {
 public:


  virtual ~printDate_getTime_presult() throw();
  std::string* success;

  _printDate_getTime_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class printDateClient : virtual public printDateIf {
 public:
  printDateClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  printDateClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getTime(std::string& _return);
  void send_getTime();
  void recv_getTime(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class printDateProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<printDateIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (printDateProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getTime(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  printDateProcessor(boost::shared_ptr<printDateIf> iface) :
    iface_(iface) {
    processMap_["getTime"] = &printDateProcessor::process_getTime;
  }

  virtual ~printDateProcessor() {}
};

class printDateProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  printDateProcessorFactory(const ::boost::shared_ptr< printDateIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< printDateIfFactory > handlerFactory_;
};

class printDateMultiface : virtual public printDateIf {
 public:
  printDateMultiface(std::vector<boost::shared_ptr<printDateIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~printDateMultiface() {}
 protected:
  std::vector<boost::shared_ptr<printDateIf> > ifaces_;
  printDateMultiface() {}
  void add(boost::shared_ptr<printDateIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getTime(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getTime(_return);
    }
    ifaces_[i]->getTime(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class printDateConcurrentClient : virtual public printDateIf {
 public:
  printDateConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  printDateConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getTime(std::string& _return);
  int32_t send_getTime();
  void recv_getTime(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
